#release configuration
#Fri Apr 24 16:35:00 CEST 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.fiji.plugin\:nnInter_Appose=0.0.3-SNAPSHOT
project.rel.fiji.plugin\:nnInter_Appose=0.0.2
project.scm.fiji.plugin\:nnInter_Appose.connection=scm\:git\:git\://github.com/ImageAnalysisHub/nnInterappose
project.scm.fiji.plugin\:nnInter_Appose.developerConnection=scm\:git\:git@github.com\:ImageAnalysisHub/nnInterappose
project.scm.fiji.plugin\:nnInter_Appose.tag=HEAD
project.scm.fiji.plugin\:nnInter_Appose.url=https\://github.com/ImageAnalysisHub/nnInterappose
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=nnInter_Appose-0.0.2
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/ImageAnalysisHub/nnInterappose
